SpriteSearch.EmptySearch=The mentioned user does not have any sprites in %arg0%'s Database. Make sure you're entering a username @ mention, or a discord user id. Epic Games usernames will __not__ work.
SpriteSearch.NoSprites=The searched user does not have any sprites in the database. They can use %arg0%the website%arg1% to import their collection.
SpriteSearch.ParseError=%arg0% failed to parse the users' Sprite collection. If this error persists, try having the user re-import their collection or contact the Owner for support.
SpriteUpdate.InvalidLevel=Please input a valid level when updating a Sprite. (0-5, 0=unowned, 5=mastery)
SpriteUpdate.NoSprites=You do not have any sprites in the database. Use %arg0%the website%arg1% to import your collection.
SpriteUpdate.ParseError=%arg0% failed to parse your Sprite collection. If this error persists, try re-importing your collection or contacting the owner for support.
SpriteUpdate.MiscFail=Failed to update the Sprite's level, make sure you selected a valid, released, Sprite.
SpriteUpdate.Success=Successfully updated %arg0% to level %arg1%.\nTo view your current collection, use the `/spritelog display` command.
SpriteImage.MessageContent=%arg0%'s Sprites
SpriteImage.FullLog=Sprite Collection Log
SpriteImage.UnownedLog=Unowned Sprite Log
SpriteImage.OwnedLog=Owned Sprite Log
SpriteImport.MiscError=There was an error importing your Sprites. Double check your input and try again.
SpriteImport.SuccessHeader=You have successfully imported your sprites:
SpriteImport.SuccessFooter=To view your Sprites, use the `/spritelog display` command.