NotAnAdmin=You must have Administrator level permissions to use this command.
EmptyCommand=Please include a command name to (un)set as Ephemeral.
NoCommandFound=Could not find command from given input.
CommandDisabled=The command `%arg0%` has been set as Public. When users run this command, everyone that can view the channel will see it.
CommandEnabled=The command `%arg0%` has been set as Ephemeral. When users run this command, it will only show for them.
Error=There was an error changing the Ephemeral status of the command. Contact my owner if this issue persists.